### ISSUE TITLE
Add an open source license

### ISSUE THREAD

**Issue by wesj** [reydanro/UIImageViewAligned#13]
I'd like to use this in a project, but the license says all rights reserved. Any chance you'd release this under Apache or something?

**Comment by reydanro** [comment]
The license is MIT, which should allow you to use the library freely.

Indeed there was an "All Rights Reserved" in the header of the source files, added by XCode automatically. I removed those lines and pushed the changes. 

I'm not a licensing expert but I guess the repository should now fall under the LICENSE file found in the root of the project.

**Comment by wesj** [comment]
Ahh. Missed that. Thanks for the change :+1:
