### ISSUE TITLE
Cocoapods?

### ISSUE THREAD

**Issue by maxpower47** [reydanro/UIImageViewAligned#14]
I see a podspec file in the repo, but I can't seem to find it on cocoapods.  Is it available there?

**Comment by krizskp** [comment]
Facing the same issue. Having to use `pod 'UIImageViewAligned', :git => 'https://github.com/reydanro/UIImageViewAligned.git'` for now.

**Comment by arielelkin** [comment]
+1

**Comment by arielelkin** [comment]
see https://github.com/reydanro/UIImageViewAligned/pull/7

**Comment by arielelkin** [comment]
@reydanro do you have any plans to support cocoapods? 

you just to get the [cocoapods trunk](https://guides.cocoapods.org/making/getting-setup-with-trunk.html) and then push a git tag.

**Comment by reydanro** [comment]
@arielelkin yes, I would like to fully support cocoapods, but unfortunately I am still without access to a Mac for the next 3-4 weeks. 
If anybody makes a pull request with the changes I would gladly merge them.

**Comment by arielelkin** [comment]
@reydanro what's needed here is to register on the cocoa pods trunk and push the git tag.

This cannot be done with a pull request as only the owner of the code can register it as a pod into the trunk (see https://guides.cocoapods.org/making/getting-setup-with-trunk.html), and only people with write access to the repo can push a git tag to it. Note that this doesn't require access to a _Mac_, it can be done from any computer that supports git.

**Comment by reydanro** [comment]
Ok, I though I needed to make some changes to the structure of the repo as well. I have access to git.
Thanks

**Comment by arielelkin** [comment]
:-)

**Comment by arielelkin** [comment]
@reydanro any updates?

**Comment by orta** [comment]
Yeah, it's worth adding @reydanro - I just spent a while looking for it. For anyone else, I'd recommend adding this to your podfile ( includes #10 )
``` ruby
pod "UIImageViewAligned", :git => "https://github.com/dbachrach/UIImageViewAligned.git"
```

**Comment by reydanro** [comment]
Thank you a million times for having this much patience.
I have now submitted the repo to cocoapods trunk. Let me know if it's visible.

PS: I relocated to another country and it took a while until I came online.

**Comment by arielelkin** [comment]
:+1:

**Comment by reydanro** [comment]
I'll take that as a confirmation and will close this and the other referenced issue.
Thanks for all your help.
