### ISSUE TITLE
Cocoapods problem

### ISSUE THREAD

**Issue by vmalov** [reydanro/UIImageViewAligned#15]
PodFile:
`source 'https://github.com/CocoaPods/Specs.git'`
`pod 'UIImageViewAligned'`

Next Problem with `pod install`:
`[!] Unable to find a specification for `UIImageViewAligned` depended upon by Podfile.`

**Comment by christ776** [comment]
Same here

**Comment by arielelkin** [comment]
see https://github.com/reydanro/UIImageViewAligned/issues/14
